In [1]:
!python --version

Python 3.14.2

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\yashp\appdata\roaming\python\python314\site-packages (2.4.4)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\yashp\appdata\roaming\python\python314\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\yashp\appdata\roaming\python\python314\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yashp\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\yashp\appdata\roaming\python\python314\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\yashp\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\yashp\appdata\roaming\python\python314\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\yashp\appdata\roaming\python\python314\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in c:\users\yashp\appdata\roaming\python\python314\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\yashp\appdata\roaming\python\python314\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\yashp\appdata\roaming\python\python314\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
import numpy as np
import sklearn

In [6]:
df = pd.read_csv("retail_store_inventory.csv")   #read csv file

In [7]:
print(df.head(10))   #read first five data from the datasets

         Date Store ID Product ID     Category Region  Inventory Level  \
0  2022-01-01     S001      P0001    Groceries  North              231
1  2022-01-01     S001      P0002         Toys  South              204
2  2022-01-01     S001      P0003         Toys   West              102
3  2022-01-01     S001      P0004         Toys  North              469
4  2022-01-01     S001      P0005  Electronics   East              166
5  2022-01-01     S001      P0006    Groceries  South              138
6  2022-01-01     S001      P0007    Furniture   East              359
7  2022-01-01     S001      P0008     Clothing  North              380
8  2022-01-01     S001      P0009  Electronics   West              183
9  2022-01-01     S001      P0010         Toys  South              108

   Units Sold  Units Ordered  Demand Forecast  Price  Discount  \
0         127             55           135.47  33.50        20
1         150             66           144.04  63.01        20
2          65             51            74.02  27.99        10
3          61            164            62.18  32.72        10
4          14            135             9.26  73.64         0
5         128            102           139.82  76.83        10
6          97            167           108.92  34.16        10
7         312             54           329.73  97.99         5
8         175            135           174.15  20.74        10
9          28            196            24.47  59.99         0

  Weather Condition  Holiday/Promotion  Competitor Pricing Seasonality
0             Rainy                  0               29.69      Autumn
1             Sunny                  0               66.16      Autumn
2             Sunny                  1               31.32      Summer
3            Cloudy                  1               34.74      Autumn
4             Sunny                  0               68.95      Summer
5             Sunny                  1               79.35      Winter
6             Rainy                  1               36.55      Winter
7            Cloudy                  0              100.09      Spring
8            Cloudy                  0               17.66      Autumn
9             Rainy                  1               61.21      Winter

In [8]:
df

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73095,2024-01-01,S005,P0016,Furniture,East,96,8,127,18.46,73.73,20,Snowy,0,72.45,Winter
73096,2024-01-01,S005,P0017,Toys,North,313,51,101,48.43,82.57,10,Cloudy,0,83.78,Autumn
73097,2024-01-01,S005,P0018,Clothing,West,278,36,151,39.65,11.11,10,Rainy,0,10.91,Winter
73098,2024-01-01,S005,P0019,Toys,East,374,264,21,270.52,53.14,20,Rainy,0,55.80,Spring
73099,2024-01-01,S005,P0020,Groceries,East,117,6,165,2.33,78.39,20,Rainy,1,79.52,Spring

In [10]:
pip install matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Collecting matplotlib
  Downloading matplotlib-3.10.8-cp314-cp314-win_amd64.whl.metadata (52 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.1-cp314-cp314-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\yashp\appdata\roaming\python\python314\site-packages (from matplotlib) (2.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\yashp\appdata\roaming\python\python314\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\yashp\appdata\roaming\python\python314\site-packages (from matplotlib) (12.2.0)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\yashp\appdata\roaming\python\python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\users\yashp\appdata\roaming\python\python314\site-packages (from seaborn) (3.0.2)
Requirement already satisfied: tzdata in c:\users\yashp\appdata\roaming\python\python314\site-packages (from pandas>=1.2->seaborn) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\yashp\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.8-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ------ --------------------------------- 1.3/8.3 MB 7.2 MB/s eta 0:00:01
   ------------- -------------------------- 2.9/8.3 MB 7.8 MB/s eta 0:00:01
   -------------------- ------------------- 4.2/8.3 MB 7.8 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.3 MB 7.7 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.3 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.3 MB 6.9 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 6.7 MB/s  0:00:01
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   -------------------------- ------------- 1.6/2.3 MB 8.2 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 8.1 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn

   ---------------------------------------- 0/7 [pyparsing]
   ---------------------------------------- 0/7 [pyparsing]
   ---------------------------------------- 0/7 [pyparsing]
   ---------------------------------------- 0/7 [pyparsing]
   ---------------------------------------- 0/7 [pyparsing]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------------- ---------------------- 3/7 [cycler]
   ---------------------- ----------------- 4/7 [contourpy]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------------- 7/7 [seaborn]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 kiwisolver-1.5.0 matplotlib-3.10.8 pyparsing-3.3.2 seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\yashp\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import matplotlib.pyplot as plt
import seaborn as sns

# Select relevant columns
corr_cols = ["Units Sold", "Price", "Discount", "Competitor Pricing"]
corr_matrix = df[corr_cols].corr()

# Heatmap
plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation between Sales and Pricing Factors")
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [10]:
fig, axes = plt.subplots(1, 3, figsize=(18,5))

sns.scatterplot(data=df, x="Price", y="Units Sold", ax=axes[0])
axes[0].set_title("Sales vs Price")

sns.scatterplot(data=df, x="Discount", y="Units Sold", ax=axes[1])
axes[1].set_title("Sales vs Discount")

sns.scatterplot(data=df, x="Competitor Pricing", y="Units Sold", ax=axes[2])
axes[2].set_title("Sales vs Competitor Pricing")

plt.show()

NameError: name 'plt' is not defined

In [11]:
import statsmodels.api as sm

X = df[["Price", "Discount", "Competitor Pricing"]]
y = df["Units Sold"]

# Add constant for intercept
X = sm.add_constant(X)

model = sm.OLS(y, X).fit()
print(model.summary())

ModuleNotFoundError: No module named 'statsmodels'

In [ ]:
pip install statsmodels

In [ ]:
print(df.head())

In [ ]:
data = df.drop(["Store ID", "Product ID", "Units Ordered", "Demand Forecast", "Price", "Discount", "Competitor Pricing"], axis=1)

In [ ]:
print(data.head(30))

In [ ]:
unique_categories = data["Category"].unique()

In [ ]:
unique_categories

In [ ]:
data["Date"] = pd.to_datetime(data["Date"])

# Add Month number column
data["Month"] = data["Date"].dt.month

In [ ]:
data

In [ ]:
combined = data.groupby(["Date", "Month", "Category", "Region"]).agg({
    "Inventory Level": "sum",
    "Units Sold": "sum",
    "Weather Condition": lambda x: x.mode()[0],   # most frequent condition
    "Holiday/Promotion": "max",                   # 1 if any promotion
    "Seasonality": lambda x: x.mode()[0]          # most frequent season
}).reset_index()

In [ ]:
combined.head(50)

In [ ]:
specific_date = "2022-02-01"
row_data = combined[combined["Date"] == specific_date]
print(row_data)

In [ ]:
combined['Inventory Level'].describe()

In [ ]:
combined['Units Sold'].describe

In [ ]:
combined.shape

In [ ]:
combined.info()

In [27]:
combined.isnull().sum()

Date                 0
Month                0
Category             0
Region               0
Inventory Level      0
Units Sold           0
Weather Condition    0
Holiday/Promotion    0
Seasonality          0
dtype: int64

In [28]:
combined.duplicated().sum()

0

In [29]:
for i in combined.select_dtypes(include="number").columns:
    sns.histplot(data=combined, x = i)
    plt.show()

NameError: name 'sns' is not defined

In [30]:
for i in combined.select_dtypes(include="number").columns:
    sns.boxplot(data=combined, x = i)
    plt.show()

NameError: name 'sns' is not defined

In [31]:
for i in ['Inventory Level', 'Holiday/Promotion']:
    sns.scatterplot(data=combined, x=i, y='Units Sold')
    plt.show()

NameError: name 'sns' is not defined

In [32]:
combined.select_dtypes(include="number").columns

Index(['Month', 'Inventory Level', 'Units Sold', 'Holiday/Promotion'], dtype='object')

In [33]:
hit_map = combined.select_dtypes(include="number").corr()
sns.heatmap(hit_map, annot=True)

NameError: name 'sns' is not defined

In [34]:
#outliers

In [35]:
import pandas as pd

# Calculate limits (25th percentile and 75th percentile)
upper_limit = combined["Inventory Level"].quantile(0.95)
lower_limit = combined["Inventory Level"].quantile(0.05)

# Clip (cap) extreme values to within limits
combined["Inventory Level Cleaned"] = combined["Inventory Level"].clip(lower=lower_limit, upper=upper_limit)

# ✅ Check results
print("Lower limit:", lower_limit)
print("Upper limit:", upper_limit)

Lower limit: 418.0
Upper limit: 2570.25

In [36]:
sns.boxplot(combined['Inventory Level Cleaned'])
plt.show()

NameError: name 'sns' is not defined

In [37]:
combined

,Date,Month,Category,Region,Inventory Level,Units Sold,Weather Condition,Holiday/Promotion,Seasonality,Inventory Level Cleaned
0,2022-01-01,1,Clothing,East,1587,947,Cloudy,1,Spring,1587.00
1,2022-01-01,1,Clothing,North,1221,861,Cloudy,0,Autumn,1221.00
2,2022-01-01,1,Clothing,South,945,483,Cloudy,1,Autumn,945.00
3,2022-01-01,1,Clothing,West,2767,1493,Snowy,1,Winter,2570.25
4,2022-01-01,1,Electronics,East,1489,1126,Sunny,1,Summer,1489.00
...,...,...,...,...,...,...,...,...,...,...
14531,2024-01-01,1,Groceries,West,1299,613,Cloudy,1,Spring,1299.00
14532,2024-01-01,1,Toys,East,1925,1032,Rainy,1,Winter,1925.00
14533,2024-01-01,1,Toys,North,1858,751,Cloudy,1,Autumn,1858.00
14534,2024-01-01,1,Toys,South,805,321,Cloudy,1,Winter,805.00
14535,2024-01-01,1,Toys,West,1783,1136,Snowy,1,Autumn,1783.00

In [38]:
combined = combined.drop(columns=["Inventory Level"])

In [39]:
#onehotencoder

In [40]:
# from sklearn.compose import make_column_transformer
# from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [41]:
# col_trans = make_column_transformer(
#     (OneHotEncoder(sparse_output=False), ['Category', 'Region', 'Weather Condition', 'Seasonality']),
#     remainder="passthrough"
# )

In [42]:
# col_trans

In [43]:
combined

,Date,Month,Category,Region,Units Sold,Weather Condition,Holiday/Promotion,Seasonality,Inventory Level Cleaned
0,2022-01-01,1,Clothing,East,947,Cloudy,1,Spring,1587.00
1,2022-01-01,1,Clothing,North,861,Cloudy,0,Autumn,1221.00
2,2022-01-01,1,Clothing,South,483,Cloudy,1,Autumn,945.00
3,2022-01-01,1,Clothing,West,1493,Snowy,1,Winter,2570.25
4,2022-01-01,1,Electronics,East,1126,Sunny,1,Summer,1489.00
...,...,...,...,...,...,...,...,...,...
14531,2024-01-01,1,Groceries,West,613,Cloudy,1,Spring,1299.00
14532,2024-01-01,1,Toys,East,1032,Rainy,1,Winter,1925.00
14533,2024-01-01,1,Toys,North,751,Cloudy,1,Autumn,1858.00
14534,2024-01-01,1,Toys,South,321,Cloudy,1,Winter,805.00
14535,2024-01-01,1,Toys,West,1136,Snowy,1,Autumn,1783.00

In [44]:
combined['Category'].unique()

array(['Clothing', 'Electronics', 'Furniture', 'Groceries', 'Toys'],
      dtype=object)

In [45]:
combined['Region'].unique()

array(['East', 'North', 'South', 'West'], dtype=object)

In [46]:
combined['Weather Condition'].unique()

array(['Cloudy', 'Snowy', 'Sunny', 'Rainy'], dtype=object)

In [47]:
combined['Seasonality'].unique()

array(['Spring', 'Autumn', 'Winter', 'Summer'], dtype=object)

In [48]:
from sklearn.preprocessing import OneHotEncoder

In [49]:
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output = False).set_output(transform='pandas')

In [50]:
ohetransform = ohe.fit_transform(combined[['Category']])

In [51]:
ohetransform

,Category_Clothing,Category_Electronics,Category_Furniture,Category_Groceries,Category_Toys
0,1.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...
14531,0.0,0.0,0.0,1.0,0.0
14532,0.0,0.0,0.0,0.0,1.0
14533,0.0,0.0,0.0,0.0,1.0
14534,0.0,0.0,0.0,0.0,1.0
14535,0.0,0.0,0.0,0.0,1.0

In [52]:
combined.head()

,Date,Month,Category,Region,Units Sold,Weather Condition,Holiday/Promotion,Seasonality,Inventory Level Cleaned
0,2022-01-01,1,Clothing,East,947,Cloudy,1,Spring,1587.00
1,2022-01-01,1,Clothing,North,861,Cloudy,0,Autumn,1221.00
2,2022-01-01,1,Clothing,South,483,Cloudy,1,Autumn,945.00
3,2022-01-01,1,Clothing,West,1493,Snowy,1,Winter,2570.25
4,2022-01-01,1,Electronics,East,1126,Sunny,1,Summer,1489.00

In [53]:
ohetransform.head()

,Category_Clothing,Category_Electronics,Category_Furniture,Category_Groceries,Category_Toys
0,1.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0

In [54]:
combined = pd.concat([combined, ohetransform], axis = 1).drop(columns = ['Category'])

In [55]:
combined.head(10)

,Date,Month,Region,Units Sold,Weather Condition,Holiday/Promotion,Seasonality,Inventory Level Cleaned,Category_Clothing,Category_Electronics,Category_Furniture,Category_Groceries,Category_Toys
0,2022-01-01,1,East,947,Cloudy,1,Spring,1587.00,1.0,0.0,0.0,0.0,0.0
1,2022-01-01,1,North,861,Cloudy,0,Autumn,1221.00,1.0,0.0,0.0,0.0,0.0
2,2022-01-01,1,South,483,Cloudy,1,Autumn,945.00,1.0,0.0,0.0,0.0,0.0
3,2022-01-01,1,West,1493,Snowy,1,Winter,2570.25,1.0,0.0,0.0,0.0,0.0
4,2022-01-01,1,East,1126,Sunny,1,Summer,1489.00,0.0,1.0,0.0,0.0,0.0
5,2022-01-01,1,North,1033,Cloudy,1,Spring,2184.00,0.0,1.0,0.0,0.0,0.0
6,2022-01-01,1,South,687,Rainy,1,Autumn,1034.00,0.0,1.0,0.0,0.0,0.0
7,2022-01-01,1,West,594,Sunny,1,Summer,1722.00,0.0,1.0,0.0,0.0,0.0
8,2022-01-01,1,East,335,Rainy,1,Autumn,995.00,0.0,0.0,1.0,0.0,0.0
9,2022-01-01,1,North,307,Cloudy,1,Summer,606.00,0.0,0.0,1.0,0.0,0.0

In [56]:
ohetransform = ohe.fit_transform(combined[['Region']])

In [57]:
combined = pd.concat([combined, ohetransform], axis = 1).drop(columns = ['Region'])

In [58]:
ohetransform = ohe.fit_transform(combined[['Weather Condition']])

In [59]:
combined = pd.concat([combined, ohetransform], axis = 1).drop(columns = ['Weather Condition'])

In [60]:
ohetransform = ohe.fit_transform(combined[['Seasonality']])

In [61]:
combined = pd.concat([combined, ohetransform], axis = 1).drop(columns = ['Seasonality'])

In [62]:
combined.to_csv('combined.csv')

In [63]:
combined.head(10)

,Date,Month,Units Sold,Holiday/Promotion,Inventory Level Cleaned,Category_Clothing,Category_Electronics,Category_Furniture,Category_Groceries,Category_Toys,...,Region_South,Region_West,Weather Condition_Cloudy,Weather Condition_Rainy,Weather Condition_Snowy,Weather Condition_Sunny,Seasonality_Autumn,Seasonality_Spring,Seasonality_Summer,Seasonality_Winter
0,2022-01-01,1,947,1,1587.00,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,2022-01-01,1,861,0,1221.00,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,2022-01-01,1,483,1,945.00,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,2022-01-01,1,1493,1,2570.25,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,2022-01-01,1,1126,1,1489.00,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
5,2022-01-01,1,1033,1,2184.00,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6,2022-01-01,1,687,1,1034.00,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
7,2022-01-01,1,594,1,1722.00,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
8,2022-01-01,1,335,1,995.00,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
9,2022-01-01,1,307,1,606.00,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [64]:
if 'Date' in combined.columns:
    combined['Date'] = pd.to_datetime(combined['Date'])
    combined = combined.sort_values('Date')

In [65]:
combined

,Date,Month,Units Sold,Holiday/Promotion,Inventory Level Cleaned,Category_Clothing,Category_Electronics,Category_Furniture,Category_Groceries,Category_Toys,...,Region_South,Region_West,Weather Condition_Cloudy,Weather Condition_Rainy,Weather Condition_Snowy,Weather Condition_Sunny,Seasonality_Autumn,Seasonality_Spring,Seasonality_Summer,Seasonality_Winter
0,2022-01-01,1,947,1,1587.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19,2022-01-01,1,1095,1,1906.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
18,2022-01-01,1,861,1,1718.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
17,2022-01-01,1,108,1,692.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
16,2022-01-01,1,346,1,633.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14517,2024-01-01,1,138,1,418.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
14516,2024-01-01,1,355,1,1206.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
14534,2024-01-01,1,321,1,805.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14524,2024-01-01,1,556,1,675.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
14535,2024-01-01,1,1136,1,1783.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0

In [66]:
y = combined['Units Sold']
X = combined.drop(columns = ['Units Sold', 'Unnamed:0'], errors = 'ignore')

print("X Shape: ", X.shape)
print("y Shape: ", y.shape)

X Shape:  (14536, 21)
y Shape:  (14536,)

In [67]:
split_idx = int(len(combined) * 0.8)
X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

print("Train size: ", X_train.shape, y_train.shape)
print("Test size: ", X_test.shape, y_test.shape)

print(X_train)

Train size:  (11628, 21) (11628,)
Test size:  (2908, 21) (2908,)
            Date  Month  Holiday/Promotion  Inventory Level Cleaned  \
0     2022-01-01      1                  1                   1587.0
19    2022-01-01      1                  1                   1906.0
18    2022-01-01      1                  1                   1718.0
17    2022-01-01      1                  1                    692.0
16    2022-01-01      1                  1                    633.0
...          ...    ...                ...                      ...
11634 2023-08-09      8                  1                    987.0
11641 2023-08-09      8                  1                   2415.0
11640 2023-08-09      8                  1                   2261.0
11639 2023-08-09      8                  1                   1430.0
11638 2023-08-09      8                  1                   1406.0

       Category_Clothing  Category_Electronics  Category_Furniture  \
0                    1.0                   0.0                 0.0
19                   0.0                   0.0                 0.0
18                   0.0                   0.0                 0.0
17                   0.0                   0.0                 0.0
16                   0.0                   0.0                 0.0
...                  ...                   ...                 ...
11634                0.0                   0.0                 1.0
11641                0.0                   0.0                 0.0
11640                0.0                   0.0                 0.0
11639                0.0                   0.0                 0.0
11638                0.0                   0.0                 0.0

       Category_Groceries  Category_Toys  Region_East  ...  Region_South  \
0                     0.0            0.0          1.0  ...           0.0
19                    0.0            1.0          0.0  ...           0.0
18                    0.0            1.0          0.0  ...           1.0
17                    0.0            1.0          0.0  ...           0.0
16                    0.0            1.0          1.0  ...           0.0
...                   ...            ...          ...  ...           ...
11634                 0.0            0.0          0.0  ...           0.0
11641                 0.0            1.0          0.0  ...           1.0
11640                 0.0            1.0          0.0  ...           0.0
11639                 0.0            1.0          1.0  ...           0.0
11638                 1.0            0.0          0.0  ...           0.0

       Region_West  Weather Condition_Cloudy  Weather Condition_Rainy  \
0              0.0                       1.0                      0.0
19             1.0                       1.0                      0.0
18             0.0                       0.0                      0.0
17             0.0                       1.0                      0.0
16             0.0                       1.0                      0.0
...            ...                       ...                      ...
11634          1.0                       0.0                      1.0
11641          0.0                       0.0                      0.0
11640          0.0                       0.0                      1.0
11639          0.0                       0.0                      0.0
11638          1.0                       0.0                      0.0

       Weather Condition_Snowy  Weather Condition_Sunny  Seasonality_Autumn  \
0                          0.0                      0.0                 0.0
19                         0.0                      0.0                 0.0
18                         0.0                      1.0                 0.0
17                         0.0                      0.0                 1.0
16                         0.0                      0.0                 0.0
...                        ...                      ...                 ...
11634                      0.0                      0.0                 1.0
11641                      1.0                      0.0                 0.0
11640                      0.0                      0.0                 0.0
11639                      0.0                      1.0                 0.0
11638                      0.0                      1.0                 0.0

       Seasonality_Spring  Seasonality_Summer  Seasonality_Winter
0                     1.0                 0.0                 0.0
19                    0.0                 0.0                 1.0
18                    0.0                 0.0                 1.0
17                    0.0                 0.0                 0.0
16                    0.0                 0.0                 1.0
...                   ...                 ...                 ...
11634                 0.0                 0.0                 0.0
11641                 0.0                 1.0                 0.0
11640                 0.0                 0.0                 1.0
11639                 0.0                 0.0                 1.0
11638                 1.0                 0.0                 0.0

[11628 rows x 21 columns]

In [68]:
pip install xgboost

Collecting xgboost
  Using cached xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from xgboost) (1.15.3)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   - -------------------------------------- 4.5/101.7 MB 22.3 MB/s eta 0:00:05
   - -------------------------------------- 5.0/101.7 MB 12.6 MB/s eta 0:00:08
   -- ------------------------------------- 5.8/101.7 MB 9.0 MB/s eta 0:00:11
   -- ------------------------------------- 6.3/101.7 MB 7.9 MB/s eta 0:00:13
   -- ------------------------------------- 7.3/101.7 MB 6.8 MB/s eta 0:00:14
   --- ------------------------------------ 8.1/101.7 MB 6.2 MB/s eta 0:00:16
   --- ------------------------------------ 8.7/101.7 MB 6.0 MB/s eta 0:00:16
   --- ------------------------------------ 9.7/101.7 MB 5.6 MB/s eta 0:00:17
   ---- ----------------------------------- 10.2/101.7 MB 5.3 MB/s eta 0:00:18
   ---- ----------------------------------- 11.0/101.7 MB 5.2 MB/s eta 0:00:18
   ---- ----------------------------------- 11.8/101.7 MB 5.1 MB/s eta 0:00:18
   ---- ----------------------------------- 12.6/101.7 MB 4.9 MB/s eta 0:00:19
   ----- ---------------------------------- 13.1/101.7 MB 4.8 MB/s eta 0:00:19
   ----- ---------------------------------- 13.9/101.7 MB 4.7 MB/s eta 0:00:19
   ----- ---------------------------------- 14.7/101.7 MB 4.6 MB/s eta 0:00:19
   ------ --------------------------------- 15.5/101.7 MB 4.5 MB/s eta 0:00:19
   ------ --------------------------------- 16.3/101.7 MB 4.5 MB/s eta 0:00:19
   ------ --------------------------------- 17.0/101.7 MB 4.5 MB/s eta 0:00:19
   ------- -------------------------------- 17.8/101.7 MB 4.4 MB/s eta 0:00:20
   ------- -------------------------------- 18.6/101.7 MB 4.4 MB/s eta 0:00:19
   ------- -------------------------------- 19.4/101.7 MB 4.4 MB/s eta 0:00:19
   ------- -------------------------------- 20.2/101.7 MB 4.3 MB/s eta 0:00:19
   -------- ------------------------------- 20.7/101.7 MB 4.3 MB/s eta 0:00:19
   -------- ------------------------------- 21.2/101.7 MB 4.2 MB/s eta 0:00:20
   -------- ------------------------------- 22.0/101.7 MB 4.1 MB/s eta 0:00:20
   -------- ------------------------------- 22.5/101.7 MB 4.1 MB/s eta 0:00:20
   --------- ------------------------------ 23.3/101.7 MB 4.1 MB/s eta 0:00:20
   --------- ------------------------------ 24.1/101.7 MB 4.1 MB/s eta 0:00:19
   --------- ------------------------------ 24.9/101.7 MB 4.1 MB/s eta 0:00:19
   ---------- ----------------------------- 25.7/101.7 MB 4.1 MB/s eta 0:00:19
   ---------- ----------------------------- 26.5/101.7 MB 4.1 MB/s eta 0:00:19
   ---------- ----------------------------- 27.5/101.7 MB 4.0 MB/s eta 0:00:19
   ----------- ---------------------------- 28.3/101.7 MB 4.1 MB/s eta 0:00:19
   ----------- ---------------------------- 29.1/101.7 MB 4.1 MB/s eta 0:00:18
   ----------- ---------------------------- 29.9/101.7 MB 4.0 MB/s eta 0:00:18
   ----------- ---------------------------- 30.4/101.7 MB 4.0 MB/s eta 0:00:18
   ------------ --------------------------- 31.2/101.7 MB 4.0 MB/s eta 0:00:18
   ------------ --------------------------- 31.7/101.7 MB 4.0 MB/s eta 0:00:18
   ------------ --------------------------- 32.2/101.7 MB 3.9 MB/s eta 0:00:18
   ------------ --------------------------- 33.0/101.7 MB 3.9 MB/s eta 0:00:18
   ------------- -------------------------- 33.8/101.7 MB 3.9 MB/s eta 0:00:18
   ------------- -------------------------- 34.3/101.7 MB 3.9 MB/s eta 0:00:18
   ------------- -------------------------- 35.1/101.7 MB 3.9 MB/s eta 0:00:18
   -------------- ------------------------- 35.7/101.7 MB 3.9 MB/s eta 0:00:18
   -------------- ------------------------- 36.2/101.7 MB 3.8 MB/s eta 0:00:18
   -------------- ------------------------- 37.0/101.7 MB 3.8 MB/s eta 0:00:17
   -------------- ------------------------- 37.7/101.7 MB 3.8 MB/s eta 0:00:17
   --------------- ------------------------ 38.5/101.7 MB 3.8 MB/s eta 0:00:17
   --------------- ------------------------ 39.3/101.7 MB 3.8 MB/s eta 0:00:17
   --------------- ------------------------ 40.1/101.7 MB 3.8 MB/s eta 0:00:17
   ---------------- ----------------------- 40.9/101.7 MB 3.8 MB/s eta 0:00:16
   ---------------- ----------------------- 41.9/101.7 MB 3.8 MB/s eta 0:00:16
   ---------------- ----------------------- 42.7/101.7 MB 3.8 MB/s eta 0:00:16
   ----------------- ---------------------- 43.8/101.7 MB 3.8 MB/s eta 0:00:16
   ----------------- ---------------------- 44.6/101.7 MB 3.9 MB/s eta 0:00:15
   ----------------- ---------------------- 45.6/101.7 MB 3.9 MB/s eta 0:00:15
   ------------------ --------------------- 46.1/101.7 MB 3.9 MB/s eta 0:00:15
   ------------------ --------------------- 46.7/101.7 MB 3.8 MB/s eta 0:00:15
   ------------------ --------------------- 46.9/101.7 MB 3.8 MB/s eta 0:00:15
   ------------------ --------------------- 47.4/101.7 MB 3.8 MB/s eta 0:00:15
   ------------------ --------------------- 48.0/101.7 MB 3.7 MB/s eta 0:00:15
   ------------------- -------------------- 48.5/101.7 MB 3.7 MB/s eta 0:00:15
   ------------------- -------------------- 49.0/101.7 MB 3.7 MB/s eta 0:00:15
   ------------------- -------------------- 49.5/101.7 MB 3.7 MB/s eta 0:00:15
   ------------------- -------------------- 50.3/101.7 MB 3.7 MB/s eta 0:00:14
   -------------------- ------------------- 50.9/101.7 MB 3.7 MB/s eta 0:00:14
   -------------------- ------------------- 51.4/101.7 MB 3.7 MB/s eta 0:00:14
   -------------------- ------------------- 52.2/101.7 MB 3.6 MB/s eta 0:00:14
   -------------------- ------------------- 52.7/101.7 MB 3.6 MB/s eta 0:00:14
   --------------------- ------------------ 53.5/101.7 MB 3.6 MB/s eta 0:00:14
   --------------------- ------------------ 54.0/101.7 MB 3.6 MB/s eta 0:00:14
   --------------------- ------------------ 54.8/101.7 MB 3.6 MB/s eta 0:00:13
   --------------------- ------------------ 55.6/101.7 MB 3.6 MB/s eta 0:00:13
   ---------------------- ----------------- 56.4/101.7 MB 3.6 MB/s eta 0:00:13
   ---------------------- ----------------- 56.9/101.7 MB 3.6 MB/s eta 0:00:13
   ---------------------- ----------------- 57.7/101.7 MB 3.6 MB/s eta 0:00:13
   ---------------------- ----------------- 58.5/101.7 MB 3.6 MB/s eta 0:00:12
   ----------------------- ---------------- 59.2/101.7 MB 3.6 MB/s eta 0:00:12
   ----------------------- ---------------- 59.8/101.7 MB 3.6 MB/s eta 0:00:12
   ----------------------- ---------------- 60.8/101.7 MB 3.6 MB/s eta 0:00:12
   ------------------------ --------------- 61.6/101.7 MB 3.6 MB/s eta 0:00:12
   ------------------------ --------------- 62.7/101.7 MB 3.6 MB/s eta 0:00:11
   ------------------------ --------------- 63.2/101.7 MB 3.6 MB/s eta 0:00:11
   ------------------------- -------------- 64.2/101.7 MB 3.6 MB/s eta 0:00:11
   ------------------------- -------------- 65.0/101.7 MB 3.6 MB/s eta 0:00:11
   ------------------------- -------------- 66.1/101.7 MB 3.7 MB/s eta 0:00:10
   -------------------------- ------------- 67.1/101.7 MB 3.7 MB/s eta 0:00:10
   -------------------------- ------------- 67.9/101.7 MB 3.7 MB/s eta 0:00:10
   --------------------------- ------------ 68.9/101.7 MB 3.7 MB/s eta 0:00:09
   --------------------------- ------------ 70.0/101.7 MB 3.7 MB/s eta 0:00:09
   --------------------------- ------------ 71.0/101.7 MB 3.7 MB/s eta 0:00:09
   ---------------------------- ----------- 72.1/101.7 MB 3.7 MB/s eta 0:00:08
   ---------------------------- ----------- 73.1/101.7 MB 3.7 MB/s eta 0:00:08
   ----------------------------- ---------- 73.9/101.7 MB 3.7 MB/s eta 0:00:08
   ----------------------------- ---------- 74.7/101.7 MB 3.7 MB/s eta 0:00:08
   ----------------------------- ---------- 75.5/101.7 MB 3.7 MB/s eta 0:00:07
   ------------------------------ --------- 76.3/101.7 MB 3.7 MB/s eta 0:00:07
   ------------------------------ --------- 76.8/101.7 MB 3.7 MB/s eta 0:00:07
   ------------------------------ --------- 77.3/101.7 MB 3.7 MB/s eta 0:00:07
   ------------------------------ --------- 78.1/101.7 MB 3.7 MB/s eta 0:00:07
   ------------------------------ --------- 78.6/101.7 MB 3.7 MB/s eta 0:00:07
   ------------------------------- -------- 79.4/101.7 MB 3.7 MB/s eta 0:00:07
   ------------------------------- -------- 80.0/101.7 MB 3.7 MB/s eta 0:00:06
   ------------------------------- -------- 80.7/101.7 MB 3.7 MB/s eta 0:00:06
   -------------------------------- ------- 81.5/101.7 MB 3.7 MB/s eta 0:00:06
   -------------------------------- ------- 82.3/101.7 MB 3.7 MB/s eta 0:00:06
   -------------------------------- ------- 82.8/101.7 MB 3.7 MB/s eta 0:00:06
   -------------------------------- ------- 83.6/101.7 MB 3.7 MB/s eta 0:00:05
   --------------------------------- ------ 84.4/101.7 MB 3.7 MB/s eta 0:00:05
   --------------------------------- ------ 85.5/101.7 MB 3.7 MB/s eta 0:00:05
   --------------------------------- ------ 86.2/101.7 MB 3.7 MB/s eta 0:00:05
   ---------------------------------- ----- 87.0/101.7 MB 3.7 MB/s eta 0:00:04
   ---------------------------------- ----- 87.8/101.7 MB 3.7 MB/s eta 0:00:04
   ---------------------------------- ----- 88.9/101.7 MB 3.7 MB/s eta 0:00:04
   ----------------------------------- ---- 89.7/101.7 MB 3.7 MB/s eta 0:00:04
   ----------------------------------- ---- 90.4/101.7 MB 3.7 MB/s eta 0:00:04
   ----------------------------------- ---- 91.5/101.7 MB 3.7 MB/s eta 0:00:03
   ------------------------------------ --- 92.0/101.7 MB 3.7 MB/s eta 0:00:03
   ------------------------------------ --- 92.5/101.7 MB 3.7 MB/s eta 0:00:03
   ------------------------------------ --- 93.3/101.7 MB 3.7 MB/s eta 0:00:03
   ------------------------------------- -- 94.1/101.7 MB 3.7 MB/s eta 0:00:03
   ------------------------------------- -- 94.9/101.7 MB 3.7 MB/s eta 0:00:02
   ------------------------------------- -- 95.4/101.7 MB 3.7 MB/s eta 0:00:02
   ------------------------------------- -- 96.2/101.7 MB 3.7 MB/s eta 0:00:02
   -------------------------------------- - 97.3/101.7 MB 3.7 MB/s eta 0:00:02
   -------------------------------------- - 98.0/101.7 MB 3.7 MB/s eta 0:00:01
   -------------------------------------- - 98.8/101.7 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  99.6/101.7 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  100.1/101.7 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  100.9/101.7 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 3.7 MB/s  0:00:27
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [69]:
pip install joblib

Requirement already satisfied: joblib in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (1.5.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [70]:
import joblib

from sklearn.model_selection import TimeSeriesSplit, RandomizedSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR

try:
    from xgboost import XGBRegressor
    xgboost_installed = True
except ImportError:
    xgboost_installed = False

In [71]:
models = {
    "Linear Regression" : Pipeline([("scaler", StandardScaler()), ("lr", LinearRegression())]),
    "Random Forest" : RandomForestRegressor(random_state = 42),
    "Gradient Boosting" : GradientBoostingRegressor(random_state = 42),
    "SVR" : Pipeline([("scaler", StandardScaler()), ("svr", SVR())]),
    "XGBoost" : XGBRegressor(random_state = 42)
}

In [72]:
X_train["Year"] = X_train["Date"].dt.year
X_train["Month"] = X_train["Date"].dt.month
X_train["Day"] = X_train["Date"].dt.day
X_train = X_train.drop(columns=["Date"])

X_test["Year"] = X_test["Date"].dt.year
X_test["Month"] = X_test["Date"].dt.month
X_test["Day"] = X_test["Date"].dt.day
X_test = X_test.drop(columns=["Date"])

C:\Users\User\AppData\Local\Temp\ipykernel_7516\1251002737.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train["Year"] = X_train["Date"].dt.year
C:\Users\User\AppData\Local\Temp\ipykernel_7516\1251002737.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train["Month"] = X_train["Date"].dt.month
C:\Users\User\AppData\Local\Temp\ipykernel_7516\1251002737.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train["Day"] = X_train["Date"].dt.day
C:\Users\User\AppData\Local\Temp\ipykernel_7516\1251002737.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test["Year"] = X_test["Date"].dt.year
C:\Users\User\AppData\Local\Temp\ipykernel_7516\1251002737.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test["Month"] = X_test["Date"].dt.month
C:\Users\User\AppData\Local\Temp\ipykernel_7516\1251002737.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test["Day"] = X_test["Date"].dt.day

In [73]:
print(y_train)

0         947
19       1095
18        861
17        108
16        346
         ...
11634     658
11641    1631
11640     932
11639     830
11638     396
Name: Units Sold, Length: 11628, dtype: int64

In [74]:
from sklearn.metrics import mean_squared_error
import numpy as np



def evaluate(y_true, y_pred):
    return {
        "R2": r2_score(y_true, y_pred),
        "RMSE": np.sqrt(mean_squared_error(y_true, y_pred)),
        "MAE": mean_absolute_error(y_true, y_pred),
    }

results = []
for name, model in models.items():
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    metrics = evaluate(y_test, preds)
    results.append({"Model": name, **metrics})

results_df = pd.DataFrame(results).sort_values("R2", ascending=False)
results_df

               Model        R2        RMSE         MAE
2  Gradient Boosting  0.716971  201.087759  156.726568
0  Linear Regression  0.711321  203.085075  157.251069
1      Random Forest  0.701761  206.420246  159.792184
4            XGBoost  0.660740  220.159042  168.960983
3                SVR  0.321436  311.362084  239.983371

In [75]:
from sklearn.model_selection import RandomizedSearchCV

param_grids = {
    "Random Forest": {"n_estimators": [50,100,200], "max_depth": [5,10,None]},
    "Gradient Boosting": {"n_estimators": [50,100,200], "learning_rate": [0.01,0.1,0.2]},
    "SVR": {"svr__C": [0.1,1,10], "svr__gamma": ["scale","auto"]},
    "XGBoost" : {"n_estimators": [50,100,200], "learning_rate": [0.01,0.1,0.2]}
}

# if xgboost_installed:
#     param_grids["XGBoost"] = {"n_estimators": [50,100,200], "learning_rate": [0.01,0.1,0.2]}

best_models = {}

for name, model in models.items():
    if name in param_grids:
        search = RandomizedSearchCV(model, param_distributions=param_grids[name], 
                                    n_iter=5, cv=TimeSeriesSplit(n_splits=3),
                                    scoring="r2", random_state=42, n_jobs=-1)
        search.fit(X_train, y_train)
        best_models[name] = search.best_estimator_
        print(f"{name}: Best params = {search.best_params_}")
    else:
        best_models[name] = model

Random Forest: Best params = {'n_estimators': 100, 'max_depth': 5}
Gradient Boosting: Best params = {'n_estimators': 200, 'learning_rate': 0.1}
SVR: Best params = {'svr__gamma': 'auto', 'svr__C': 10}
XGBoost: Best params = {'n_estimators': 200, 'learning_rate': 0.1}

In [76]:
final_results = []
for name, model in best_models.items():
    preds = model.predict(X_test)
    metrics = evaluate(y_test, preds)
    final_results.append({"Model": name, **metrics})

pd.DataFrame(final_results).sort_values("R2", ascending=False)

               Model        R2        RMSE         MAE
1      Random Forest  0.718616  200.502602  156.201336
2  Gradient Boosting  0.714124  202.096471  157.190975
0  Linear Regression  0.711321  203.085075  157.251069
4            XGBoost  0.692713  209.528097  161.765076
3                SVR  0.661425  219.936688  168.072567

In [77]:
best_model_name = pd.DataFrame(final_results).sort_values("R2", ascending=False).iloc[0]["Model"]
best_model = best_models[best_model_name]

# best_model_name = "XGBoost"
# best_model = best_models[best_model_name]

# joblib.dump(best_model, "best_sales_model.joblib")
# print(f"Saved best model: {best_model_name}")

In [78]:
# XGBoost ='XGBoost'

In [79]:
# joblib.dump(XGBoost, "xgboost_sales_model.joblib")

# print("Saved XGBoost model as xgboost_sales_model.joblib")

In [80]:
import pickle as pk

In [81]:
pk.dump(best_model,open('Sales_model.pkl','wb'))

In [82]:
input = pd.DataFrame([[	1,1,1500.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,2025,1]],columns=['Month','Holiday/Promotion','Inventory Level Cleaned','Category_Clothing','Category_Electronics','Category_Furniture','Category_Groceries','Category_Toys','Region_East','Region_North','Region_South','Region_West','Weather Condition_Cloudy','Weather Condition_Rainy','Weather Condition_Snowy','Weather Condition_Sunny','Seasonality_Autumn','Seasonality_Spring','Seasonality_Summer','Seasonality_Winter','Year','Day'])

In [83]:
best_model.predict(input)

array([773.40012255])

In [84]:
combined.to_csv("combined2.csv")